controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

    # PID gains for each joint (can be adjusted as needed)
    gains:
      joint1:
        p: 0.1
        i: 0.01
        d: 0.001
        i_max: 1.0
        i_min: -1.0
      joint2:
        p: 0.1
        i: 0.01
        d: 0.001
        i_max: 1.0
        i_min: -1.0


    # State and action monitoring
    state_publish_rate: 50.0  # Hz
    action_monitor_rate: 20.0  # Hz

    # Additional configuration parameters
    allow_partial_joints_goal: false
    hardware_state_has_offset: false
    deduce_states_from_derivatives: false

    constraints:
      stopped_velocity_tolerance: 0.01
      allow_nonzero_velocity_at_trajectory_end: true
